framework:
    cache:
        app: app.cache.adapter.redis
        default_redis_provider: app.redis_provider
        prefix_seed: 'symfony-api'
        pools:
            cache.redis:
                adapter: app.cache.adapter.redis

services:
    app.redis_provider:
        class: \Redis
        factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments:
            - 'redis://redis:6379'
            - { retry_interval: 2, timeout: 10 }
    
    app.cache.adapter.redis:
        parent: 'cache.adapter.redis'
        tags:
            - { name: 'cache.redis', namespace: 'cache_redis' }
