gesdinet_jwt_refresh_token:
    firewall: api
    ttl: 315_360_000 # Durée de vie de 10 ans
    refresh_token_class: App\Entity\RefreshToken
    token_parameter_name: refresh_token
    user_identity_field: username
    user_provider: security.providers.app_user_provider
