mercure:
    hubs:
        default:
            url: '%env(MAIN_URL)%/.well-known/mercure'
            public_url: '%env(MAIN_URL)%/.well-known/mercure'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: '*'
