nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:8080', 'https://localhost', 'https://prive.pifpafdeluxe.fr', 'http://prive.pifpafdeluxe.fr:8080', 'https://192.168.0.210', 'http://192.168.0.210:8080']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': # Permettre CORS pour toutes les routes
            allow_origin: ['http://localhost:3000', 'http://192.168.1.100:3000', 'http://your-public-ip:3000']
